version: '3.9'

services:
  db-endereco:
    image: postgres:16.2
    restart: always
    container_name: db-endereco
    environment:
      POSTGRES_DB: enderecos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - C:/Projetos/PostgresData/Enderecos:/var/lib/postgresql/data

  db-pessoa:
    image: postgres:16.2
    restart: always
    container_name: db-pessoa
    environment:
      POSTGRES_DB: pessoas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - C:/Projetos/PostgresData/Pessoas:/var/lib/postgresql/data
    depends_on:
      - db-endereco

networks:
  default:
    name: local-network
    external: true