version: '3.9'
services:
  db:
    image: postgres:16.2
    restart: always
    container_name: db-endereco
    environment:
      POSTGRES_DB: enderecos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - C:/Projetos/PostgresData:/var/lib/postgresql/data
