server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: modulo-endereco
          uri: http://localhost:8081
          predicates:
            - Path=api/v1/estados/**
            - Path=api/v1/municipios/**
            - Path=api/v1/enderecos/**
        - id: modulo-pessoa
          uri: lb://MODULO-PESSOA
          predicates:
            - Path=api/v1/pessoas/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost