server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  #main:
  #  web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: modulo-endereco
          uri: lb://MODULO-ENDERECO
          predicates:
            - Path=/api/v1/estados/**
            - Path=/api/v1/municipios/**
            - Path=/api/v1/enderecos/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost